In [23]:
import os 
import pandas as pd

base_url = "C:/Users/scsoo/OneDrive/바탕 화면/sample-data-master/sample-data-master/anime"
anime_csv = os.path.join(base_url, 'anime.csv')

df = pd.read_csv(anime_csv)
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [25]:
df = pd.read_csv(anime_csv, index_col = 0)
df.head()

,name,genre,type,episodes,rating,members
anime_id,,,,,,
32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [33]:
df = pd.read_csv(anime_csv, index_col = 'name',dtype = {'members':float})
df.head()

,anime_id,genre,type,episodes,rating,members
name,,,,,,
Kimi no Na wa.,32281,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0
Fullmetal Alchemist: Brotherhood,5114,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665.0
Gintama°,28977,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262.0
Steins;Gate,9253,"Sci-Fi, Thriller",TV,24,9.17,673572.0
Gintama&#039;,9969,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266.0

In [37]:
anime_stock_price_csv = os.path.join(base_url, 'anime_stock_price.csv')
df = pd.read_csv(anime_stock_price_csv, parse_dates=['Date'])
df.dtypes

Date              datetime64[ns]
TOEI ANIMATION           float64
IG Port                  float64
dtype: object

In [39]:
anime_tsv = os.path.join(base_url, 'anime.tsv')
df = pd.read_csv(anime_tsv, sep='\t')